---
title: Optimizing Social Distance Keeping in Indoor Environments via a Public Display
  Navigation Support System - Investigations with R
author: "Christian Terbeck (christian.terbeck@uni-muenster.de)"
date: "January 27, 2022"
output:
  pdf_document: default
  html_document:
    df_print: paged
---
    
### Introduction
    
This RMarkdown file was created during the work on my master thesis with the title "Optimizing Social Distance Keeping in Indoor Environments via a Public Display Navigation Support System".
It may help to understand the analysis of the NetLogo model (ABM), to calculate own results or may be used for future research.
Be aware that these simulations are computationally intensive and that it might take hours for them to complete.

### Preparation
  
Is necessary, clean up the environment by executing:
  
```
rm(list=ls())
```

Install the NLRX package to execute NetLogo models from RStudio.
Then Use NLRX library.

```
install.packages("nlrx")
library(nlrx)
```

Set NetLogo settings according to NLRX documentation (you may adjust these values to your own needs)

```
netlogopath <- file.path("C:/Program Files/NetLogo 6.1.0")
modelpath <- file.path("C:/Users/chris/github/master/model6-1.nlogo")
outpath <- file.path("C:/Users/chris/github/master/output/r")
```

Set nl object. Note: NetLogo 6.1 is currently the highest supported version.
(Thats why there is an executable 6.1 version of my model within the directory.)

```
nl <- nl(nlversion = "6.1.0",
         nlpath = netlogopath,
         modelpath = modelpath,
         jvmmem = 1024)
```

Check if nl object can initialize without errors.
Have a closer look at the checklist to see what might went wrong.

```
print(nl)
```

## Hospital scenario

### Distinct analysis

Set up the experiment based on the NetLogo model.

```
nl@experiment <- experiment(expname = "hospital",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "true",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = c(5000, 10000, 15000, 20000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("dynamic-signage-rate"= list(values = c(0, 0.25, 0.5, 0.75, 1))),
                            constants = list("scenario" = "\"hospital\"",
                                             "dt" = 1,
                                             "V0" = 1,
                                             "A" = 1,
                                             "D" = 2,
                                             "Tr" = 1,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 4,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 180,
                                             "mean-treatment-time" = 15,
                                             "mean-visiting-time" = 45,
                                             "max-visiting-time" = 60,
                                             "max-capacity" = 120,
                                             "area-of-awareness" = 10,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "true",
                                             "mean-waiting-tolerance" = 195,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 0,
                                             "mean-passenger-number" = 0))
```

Check if all variables and constants are assigned correctly:

```
eval_variables_constants(nl)
```

Set up simulation design:
  
```
nl@simdesign <- simdesign_distinct(nl = nl, nseeds = 30)
```

Check for errors again:
  
```
print(nl)
```

Run the analysis:
  
```
results <- run_nl_all(nl = nl)
```

You may store the results in a separate variable so it does not get replaced when running another simulation:
  
```
results_hospital <- results
```

#### Sensitivity analysis

Setting up experiment for sensitivity analysis:


```
nl@experiment <- experiment(expname = "hospital",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "false",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = seq(5000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("dynamic-signage-rate" = list(min = 0, max = 1, qfun = "qunif")),
                            constants = list("scenario" = "\"hospital\"",
                                             "dt" = 1,
                                             "V0" = 1,
                                             "A" = 1,
                                             "D" = 2,
                                             "Tr" = 1,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 4,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 180,
                                             "mean-treatment-time" = 15,
                                             "mean-visiting-time" = 45,
                                             "max-visiting-time" = 60,
                                             "max-capacity" = 120,
                                             "area-of-awareness" = 10,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "true",
                                             "mean-waiting-tolerance" = 195,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 0,
                                             "mean-passenger-number" = 0))
```

Latin hypercube sampling (sensitivity analysis):

```
nl@simdesign <- simdesign_lhs(nl=nl,
                              samples=5,
                              nseeds=10,
                              precision=3)
```
Experiment setup for area of awareness optimization

```
nl@experiment <- experiment(expname = "hospital",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "false",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = seq(5000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("area-of-awareness" = list(min = 5, max = 15, qfun = "qunif")),
                            constants = list("scenario" = "\"hospital\"",
                                             "dt" = 1,
                                             "V0" = 1,
                                             "A" = 1,
                                             "D" = 2,
                                             "Tr" = 1,
                                             "dynamic-signage-rate" = 1,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 4,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 180,
                                             "mean-treatment-time" = 15,
                                             "mean-visiting-time" = 45,
                                             "max-visiting-time" = 60,
                                             "max-capacity" = 120,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "true",
                                             "mean-waiting-tolerance" = 195,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 0,
                                             "mean-passenger-number" = 0))
```

Sobol sensitivity analysis for parameter optimization:

```
nl@simdesign <- simdesign_sobol(nl=nl,
                                samples=10,
                                sobolorder=1,
                                sobolnboot=100,
                                sobolconf=0.95,
                                nseeds=3,
                                precision=3)
```

Check for errors again:

```
print(nl)
```

Compute results:

```
analysis_hospital <- run_nl_all(nl = nl)
```

Transfer results to another variable again:
  
```
analysis_hospital <- analysis
```

## Airport scenario

### Distinct analysis

Set up the experiment based on the NetLogo model.

```
nl@experiment <- experiment(expname = "airport",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "true",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = c(5000, 10000, 15000, 20000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "round arrival-contacts / 2", "round departure-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("dynamic-signage-rate"= list(values = c(0, 0.25, 0.5, 0.75, 1))),
                            constants = list("scenario" = "\"airport\"",
                                             "dt" = 1,
                                             "V0" = 1.2,
                                             "A" = 2,
                                             "D" = 2,
                                             "Tr" = 1.3,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 0,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 4,
                                             "mean-treatment-time" = 0,
                                             "mean-visiting-time" = 0,
                                             "max-visiting-time" = 0,
                                             "max-capacity" = 2000,
                                             "area-of-awareness" = 22,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "false",
                                             "mean-waiting-tolerance" = 600,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 6,
                                             "mean-passenger-number" = 110))
```

Check if all variables and constants are assigned correctly:
  
```
eval_variables_constants(nl)
```

Set up simulation design:
  
```
nl@simdesign <- simdesign_distinct(nl = nl, nseeds = 30)
```

Check for errors again:
  
```
print(nl)
```

Run the analysis:
  
```
results <- run_nl_all(nl = nl)
```

You may store the results in a separate variable so it does not get replaced when running another simulation:
  
```
results_airport <- results
```

#### Sensitivity analysis

Setting up experiment for sensitivity analysis:
  
  
```
nl@experiment <- experiment(expname = "airport",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "false",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = seq(5000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "round arrival-contacts / 2", "round departure-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("dynamic-signage-rate" = list(min = 0, max = 1, qfun = "qunif")),
                            constants = list("scenario" = "\"airport\"",
                                             "dt" = 1,
                                             "V0" = 1.2,
                                             "A" = 2,
                                             "D" = 2,
                                             "Tr" = 1.3,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 0,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 4,
                                             "mean-treatment-time" = 0,
                                             "mean-visiting-time" = 0,
                                             "max-visiting-time" = 0,
                                             "max-capacity" = 2000,
                                             "area-of-awareness" = 22,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "false",
                                             "mean-waiting-tolerance" = 600,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 6,
                                             "mean-passenger-number" = 110))
```

Latin hypercube sampling (sensitivity analysis):
  
```
nl@simdesign <- simdesign_lhs(nl=nl,
                              samples=5,
                              nseeds=10,
                              precision=3)
```
Prepare experiment for airport area of awareness optimization:

```
nl@experiment <- experiment(expname = "airport",
                            outpath = outpath,
                            repetition = 1,
                            tickmetrics = "false",
                            idsetup = "setup",
                            idgo = "simulate",
                            runtime = 20000,
                            evalticks = seq(5000),
                            metrics = c("time", "dynamic-signage-rate * 100", "round overall-contacts / 2", "round visitor-contacts / 2", "round visitor-staff-contacts / 2", "round staff-contacts / 2", "round no-staff-only-contacts / 2", "round unique-contacts / 2", "round critical-contacts / 2", "round arrival-contacts / 2", "round departure-contacts / 2", "avg-contact-time", "avg-contact-distance", "total-number-of-visitors"),
                            variables = list("area-of-awareness" = list(min = 10, max = 30, qfun = "qunif")),
                            constants = list("scenario" = "\"airport\"",
                                             "dt" = 1,
                                             "V0" = 1.2,
                                             "A" = 2,
                                             "D" = 2,
                                             "Tr" = 1.3,
                                             "dynamic-signage-rate" = 1,
                                             "initial-number-of-visitors" = 0,
                                             "staff-members-per-level" = 0,
                                             "staff-switches-levels?" = "false",
                                             "spawn-rate" = 4,
                                             "mean-treatment-time" = 0,
                                             "mean-visiting-time" = 0,
                                             "max-visiting-time" = 0,
                                             "max-capacity" = 2000,
                                             "angle-of-awareness" = 15,
                                             "use-stop-feature?" = "false",
                                             "mean-waiting-tolerance" = 600,
                                             "show-areas-of-awareness?" = "false",
                                             "use-static-signage?" = "false",
                                             "consider-people-at-adjacent-displays?" = "true",
                                             "force-all-visitors-to-stick-to-one-ways?" = "true",
                                             "scan-movement-directions?" = "true",
                                             "contact-radius" = 1.5,
                                             "critical-period" = 15,
                                             "contact-tolerance" = 2,
                                             "show-circles?" = "false",
                                             "show-paths?" = "false",
                                             "show-walking-paths?" = "false",
                                             "show-logs?" = "false",
                                             "show-contacts?" = "false",
                                             "show-labels?" = "false",
                                             "enable-gis-extension?" = "false",
                                             "write-output?" = "false",
                                             "output-steps" = 1000,
                                             "stop-at-ticks" = 0,
                                             "gate-open-period" = 6,
                                             "mean-passenger-number" = 110))
```

Sobol sensitivity analysis for parameter optimization:

```
nl@simdesign <- simdesign_sobol(nl=nl,
                              samples=10,
                              sobolorder=1,
                              sobolnboot=100,
                              sobolconf=0.95,
                              nseeds=3,
                              precision=3)
```

Check for errors again:
  
```
print(nl)
```

Compute results:
  
```
analysis_airport <- run_nl_all(nl = nl)
```

Transfer results to another variable again:
  
```
analysis_airport <- analysis
```

### Plot results

```
results <- analysis_airport
```

As a regular plot:

```
plot(results$`dynamic-signage-rate * 100`, results$`round overall-contacts / 2`,
     xlab="People who follow dynamic signage (%)",
     ylab="Contacts",
     main="Overall contacts")
```

And as a boxplot:

```
boxplot(results$`round overall-contacts / 2`~results$`dynamic-signage-rate * 100`,
     xlab="People who follow dynamic signage (%)",
     ylab="Contacts",
     main="Overall contacts")
```

If multiple records have been created that result in several timesteps in one dataset, you may want to use (adjust the lines to your needs to specify the values you would like to investigate):
  
```
step <- 20000
results <- results_hospital
```

```
plot(results[results$`[step]` == step,]$`dynamic-signage-rate * 100`, results[results$`[step]` == step,]$`round overall-contacts / 2`,
     xlab="People who follow dynamic signage (%)",
     ylab="Contacts",
     main="Overall contacts")
```

And for boxplot:
  
```
boxplot(results[results$`[step]` == step,]$`round overall-contacts / 2`~results[results$`[step]` == step,]$`dynamic-signage-rate * 100`,
        xlab="People who follow dynamic signage (%)",
        ylab="Contacts",
        main="Overall contacts")
```

In case of different scenarios you may also want to create different plots.
When plotting the hospital results you may want to create another plot without the staff contacts, and when doing the airport results you may want to distinguish between arrival and departure floor.

### Additional code for writing output and attaching results to simdesign object

Attach simulation, write output and analyze data:

```
setsim(nl, "simoutput") <- results
write_simoutput(nl)
analyze_nl(nl)
```